
/**
 * Competitions.
 */

export const SET_COMPETITIONS = 'SET_COMPETITIONS'
export const LOAD_COMPETITIONS = 'LOAD_COMPETITIONS'
export const RESET_COMPETITIONS = 'RESET_COMPETITIONS'

/**
 * Promoters.
 */

export const SET_PROMOTERS = 'SET_PROMOTERS'
export const LOAD_PROMOTERS = 'LOAD_PROMOTERS'

/**
 * Modals.
 */

export const SET_ACTIVE_MODAL = 'SET_ACTIVE_MODAL'
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODALS = 'HIDE_MODALS'

/**
 * User.
 */

export const USER_CONNECT_TWITTER = 'USER_CONNECT_TWITTER'
export const USER_AUTHORISE_TWITTER = 'USER_AUTHORISE_TWITTER'
export const USER_SET_TOKEN = 'USER_SET_TOKEN'
export const USER_UPDATE_TIMESTAMPS = 'USER_UPDATE_TIMESTAMPS'
